# Site settings
title: bennettchidoro.com
email: bchidoro9@gmail.com
description: The highest human act is to inspire.
# logo: /assets/images/logo.png
url: https://www.bennettchidoro.com # the base hostname & protocol for your site, e.g. http://example.com
author: Bennett Chidoro
repository: bc3209/bennettchidoro.com
timezone: America/New_York
host: 0.0.0.0 # This lets us test on devices locally. See http://stackoverflow.com/a/16608698/1154642
github:
  url: http://localhost:4000 # This gets overridden when the site is deployed on github pages

# Build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-relative-links
exclude:
  - Gemfile
  - Gemfile.lock
  - readme.md
  - CNAME
sass:
  sass_dir: assets/_sass
  style: compressed
include: ['_pages']
# See HTML compression settings at http://jch.penibelst.de/#configuration
#   Don't use inline javascript slash-comments with this enabled (`//`), or you'll
#   see JS errors. See other caveauts here: http://jch.penibelst.de/#restrictions
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [html, head, body]
  ignore:
    envs: []
  blanklines: false
  profile: false

# Content settings
permalink: pretty

# Custom Vars
branch: master # the branch my live site is deployed to.

github: [metadata]
